### ISSUE TITLE
FileNotFoundErrpr: Errno 2

### ISSUE THREAD

**Issue by sunrael** [voyageur/dagr#34] opened 2018-11-05 22:47 UTC
![dagr issue](https://user-images.githubusercontent.com/33880699/48031324-c8924680-e121-11e8-8c68-31cfbefb47ff.PNG)

I have been recieving this error in V3.6 and 2.7.  Wondering if there is a simple work around.  Fairly new to python.  Thank you for any assistance.

**Comment by kannabianka** [comment] 2018-11-08 11:01
The same is happening to me.
I believe this is since deviantart changed the naming convention... from the download button, almost everything besides some rare exceptions, the file is named "file.jfif"

thanks for any assistance

**Comment by voyageur** [comment] 2018-11-08 22:55
OK last changes should fix it, let's keep one single issue to track this. If current git code does not work (apart from strange filenames, still in progress), don't hesitate to reopen!

**Comment by voyageur** [comment] 2018-11-08 22:55
Duplicate of #33

**Closed** 2018-11-08 22:55 UTC
